### ISSUE TITLE
Error with sort when processes goes away during the run.

### ISSUE THREAD

**Issue by Jehreg** [simondeziel/check-deleted-libs#5]
We got the following error:
```
root@pgsql:~# /usr/sbin/check-deleted-libs
sort: open failed: 114686/comm: No such file or directory
```

This give us a non 0 error code on exit.

**Comment by simondeziel** [comment]
Thanks

**Comment by Jehreg** [comment]
Can you tag a new version, at your leisure ?
Then I will have to figure out how to bring it into the PPA.
Thanks

**Comment by simondeziel** [comment]
@Jehreg, done https://github.com/simondeziel/check-deleted-libs/releases/tag/0.6
